### ISSUE TITLE
Possible unnecessary page refresh

### ISSUE THREAD

**Issue by NduatiK** [councilofelders/numerbay#218]
I found your solution to the [MetaMask extension issue](https://github.com/MetaMask/metamask-extension/issues/9407) while trying to address it for our team. Just wanted to suggest a tweak to avoid an extra page reload.

Right now you are doing:
https://github.com/councilofelders/numerbay/blob/9a216a1457a662a663e2f3b060f3308184b8f451/frontend/packages/theme/plugins/wallet.js#L58-L67

But line 65 always executes if ethereum was not immediately. 

You might want to do the following since ethereum might have initialized between starting the 10 second timer and it finishing.
```
 const waitSeconds = 10; 
 if (typeof window !== "undefined" && typeof window.ethereum !== 'undefined' &&  !window.ethereum._state.initialized) { 
   while(!ethereum._state.initialized) { 
     await new Promise(resolve => setTimeout(resolve, waitSeconds * 1000)); 
     // window.location.reload(); 
     if (!ethereum._state.initialized) {
        window.location.search += '&retry=true';
     }
   } 
 } 
```

**Comment by restrading** [comment]
Thanks @NduatiK I will address this issue.

**Comment by NduatiK** [comment]
Nice! I had closed this to do some investigation on our codebase first. Thanks for handling the PR
