### ISSUE TITLE
Submission of artifact stuck in queued state

### ISSUE THREAD

**Issue by restrading** [councilofelders/numerbay#29]
There is likely a logical bug for the "submit" button in unencrypted artifacts that causes a submission to be stuck at "queued" even if a file becomes available

**Comment by pelletgu** [comment]
Hi restrading, i hope it's fixed. Thanks in advance! Finally will i get a partial refund or a one week extension?

**Comment by restrading** [comment]
It should be fixed, every click of the submit button should trigger a retry regardless if it's already queued. Let me know if you encounter issues.

I have not heard back from numeraibr and just sent a follow up, will let you know if they respond, you can also try to reach out through rocketchat, same ID. Sorry about that.

**Comment by pelletgu** [comment]
No worries, i will care of finding a solution with him. Thanks for your work. It looks like it works fine

**Comment by restrading** [comment]
@pelletgu ok, if they are ok to extend the order by one round, just let me know and I will extend it for you.
