### ISSUE TITLE
using the numerbay API in a numerai compute node failure

### ISSUE THREAD

**Issue by simpsus** [councilofelders/numerbay#5]
when adding numerbay to the requirements.txt file of a compute node, the test of the node fails with

[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:     from numerbay import NumerBay
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:   File "/usr/local/lib/python3.7/site-packages/numerbay/__init__.py", line 12, in <module>
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:     from numerbay.numerbay import NumerBay, API_ENDPOINT_URL
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:   File "/usr/local/lib/python3.7/site-packages/numerbay/numerbay.py", line 17, in <module>
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:     from numerbay import utils
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:   File "/usr/local/lib/python3.7/site-packages/numerbay/utils.py", line 15, in <module>
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000:     import nacl.utils
[ecs/numerai-elwetritsche/e00f3057d6e74ac6aa19be18bef7811d] 2022-02-18 22:57:59.170000: ModuleNotFoundError: No module named 'nacl'

The code lines used in the predict.py file are exactly the ones from the numerbay tutorial.
adding nacl to the requirements.txt file fails with ModulNotFoundError: No module named "acl"

**Comment by simpsus** [comment]
the package to add to the requirements.txt is called pynacl

why it is not pulled automatically as a dependency is beyond me

**Comment by simpsus** [comment]
Also, apologies for opening this issue in the wrong repo.

**Comment by restrading** [comment]
@simpsus No worries, is the problem resolved? If not, I will try to reproduce it on my end

**Comment by restrading** [comment]
@simpsus also, did you happen to install the package with --no-deps flag? That might be one reason why deps are not pulled.
